<?php
/**
 * Email template for notifying a user about an API token generated by an admin.
 *
 * @var string $user_name The name of the user the token is generated for.
 * @var string $generated_by The name of the admin who generated the token.
 * @var string $token_name The name of the token.
 * @var string $token The actual API token.
 * @var array $apis List of APIs the token has access to.
 * @var \Carbon\Carbon|null $expires_at The expiration date of the token, if applicable.
 */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>API Token</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px 20px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .content {
            padding: 30px 20px;
        }
        .token-box {
            background: #f8f9fa;
            border: 2px dashed #007bff;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
            font-family: 'Courier New', monospace;
            word-break: break-all;
            position: relative;
        }
        .token-text {
            font-size: 14px;
            color: #dc3545;
            font-weight: bold;
        }
        .copy-notice {
            background: #fff3cd;
            border: 1px solid #ffeaa7;
            color: #856404;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
        }
        .api-list {
            background: #e8f5e8;
            border-left: 4px solid #28a745;
            padding: 15px;
            margin: 15px 0;
        }
        .api-list ul {
            margin: 0;
            padding-left: 20px;
        }
        .footer {
            background: #f8f9fa;
            padding: 20px;
            text-align: center;
            font-size: 12px;
            color: #6c757d;
        }
        .btn {
            display: inline-block;
            padding: 12px 24px;
            background: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin: 10px 0;
        }
        .warning {
            background: #f8d7da;
            border: 1px solid #f5c6cb;
            color: #721c24;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔑 API Pristupni Token</h1>
            <p>Kreiran od strane administratora</p>
        </div>

        <div class="content">
            <p>Pozdrav <strong>{{ $user_name }}</strong>,</p>

            <p>Administrator <strong>{{ $generated_by }}</strong> je kreirao API token za vas:</p>

            <div class="copy-notice">
                <strong>⚠️ VAŽNO:</strong> Ovaj token će biti prikazan samo jednom. Molimo vas da ga odmah kopirate i bezbedno sačuvate.
            </div>

            <div class="token-box">
                <strong>Token Name:</strong> {{ $token_name }}<br><br>
                <strong>Vaš Token:</strong><br>
                <div class="token-text">{{ $token }}</div>
            </div>

            <div class="api-list">
                <strong>📋 Pristup odobren za sledeće API-jeve:</strong>
                <ul>
                    @foreach($apis as $api)
                        <li><code>{{ $api }}</code></li>
                    @endforeach
                </ul>
            </div>

            @if($expires_at)
            <div class="warning">
                <strong>⏰ Token ističe:</strong> {{ \Carbon\Carbon::parse($expires_at)->format('d.m.Y H:i') }}
            </div>
            @endif

            <h3>📖 Kako koristiti token:</h3>
            <ol>
                <li>Kopirajte token iz crvenog okvira iznad</li>
                <li>U vašoj aplikaciji dodajte header: <code>Authorization: Bearer {token}</code></li>
                <li>Pozovite API endpoints na: <code>https://etg.dmx.rs/api/</code></li>
            </ol>

            <h3>🚀 Primer korišćenja:</h3>
            <div class="token-box">
curl -H "Authorization: Bearer {{ $token }}" \<br>
&nbsp;&nbsp;&nbsp;&nbsp;https://etg.dmx.rs/api/{{ $apis[0] ?? 'api-name' }}/v1/endpoint
            </div>

            <div style="text-align: center; margin: 30px 0;">
                <a href="https://docs.dmx.rs" class="btn">📚 Pogledaj Dokumentaciju</a>
            </div>
        </div>

        <div class="footer">
            <p>Ovaj email je automatski generisan od strane Delmax API sistema.<br>
            Za pomoć kontaktirajte: <a href="mailto:api-support@delmax.rs">api-support@delmax.rs</a></p>
        </div>
    </div>
</body>
</html>
